version: '3.8'

services:
  devgrid:
    build: devgrid
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 "devgrid:create_app('DevConfig')" --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
    restart: always
    ports:
      - 5000
    environment:
      - APP_NAME="interview"
      - DEBUG=True
      - APP_LONG_NAME="Interview Test"
      - SECRET_KEY=brunoromano
  proxy:
    build: front
    restart: always
    ports:
      - 80:80
    depends_on:
      - devgrid
