version: '3.8'

services:
  devgrid:
    build: devgrid
    command: gunicorn --workers 2 --bind 0.0.0.0:5000 "devgrid:create_app('DevConfig')" --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
    restart: always
    ports:
      - 5000
    environment:
      - APP_NAME="interview"
      - DEBUG=True
      - APP_LONG_NAME="Interview Test"
      - SECRET_KEY=brunoromano
      - OPEN_WEATHER_MAP_KEY=faaa4db2caf0f9b313de58597b797fba
      - DEFAULT_CACHE_TTL=300
      - DEFAULT_MAX_NUMBER=5
  proxy:
    build: front
    restart: always
    ports:
      - 8080:80
    depends_on:
      - devgrid
