# This is a basic workflow to help you get started with Actions

name: cd-github

# 1
# Control when this workflow will be triggered...
# Just when CI runs successfully, and a push to main
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2 default environments
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write
  contents: read

#3 jobs
jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: latest

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            devgrid:latest
            devgrid:v-1
