# This is a basic workflow to help you get started with Actions

name: CD

# 1
# Control when this workflow will be triggered...
# Just when CI runs successfully, and a push to main
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2 default environments
env:
  REGISTRY: "ghcr.io"

#3 jobs
jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: ./devgrid
          push: true
          tags: devgrid/back:latest

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: myimage
#          path: /tmp/myimage.tar
