# This is a basic workflow to help you get started with Actions

name: cd-github

# 1
# Control when this workflow will be triggered...
# Just when CI runs successfully, and a push to main
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2 default environments
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

#3 jobs
jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: ./devgrid
          push: true
          tags: bromano/back:latest
